version: "3.8"

services:
  # service-a:
  #   build:
  #     context: ./
  #   ports:
  #     - 8080:8080

  # service-b:
  #   build:
  #     context: ./
  jaeger:
    image: jaegertracing/all-in-one:1.35
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
  
  golang-dev:
    image: golang:1.20
