version: "3.8"

services:
  # service-a:
  #   build:
  #     context: ./
  #   ports:
  #     - 8080:8080
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  service-b:
    build:
      context: ./
    command: 'go run .'
    volumes:
      - ./:/app
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - 16686:16686

  oap:
    image: apache/skywalking-oap-server:9.5.0
    environment:
      - SW_OTEL_RECEIVER=default
      - SW_OTEL_RECEIVER_ENABLED_OC_RULES=vm
  
  oap-ui:
    image: apache/skywalking-ui:9.5.0
    ports:
      - 9090:8080
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
  
  golang-dev:
    image: golang:1.20
    environment:
      - SW_AGENT_REPORTER_GRPC_BACKEND_SERVICE=http://oap:12800

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"

  otel-collector:
    image: otel/opentelemetry-collector:0.82.0 
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" 
      - "55678"
